apiVersion: v1
kind: Pod
metadata:
  name: busypod-priliveged
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["sh", "-c", 'while true; do echo "Running..."; sleep 2h; done']
      imagePullPolicy: Always
      securityContext:
        privileged: true
        runAsUser: 0
        allowPrivilegeEscalation: true
        readOnlyRootFilesystem: false
        capabilities:
          add: ["CAP_SYS_BOOT"]